### ISSUE TITLE
Webapp not loading in safari

### ISSUE THREAD

**Issue by maticrivo** [nisrulz/javadoc-themer#2]
Hey, the webapp is not loading in Safari. I can see in the console the following errors:

```
[Error] Blocked a frame with origin "http://crushingcode.byethost5.com" from accessing a frame with origin "http://javadocthemer.crushingcode.co". Protocols, domains, and ports must match.
[Error] Refused to display 'https://support.google.com/accounts/answer/61416' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

**Comment by nisrulz** [comment]
Hi @maticrivo , its happening because your safari doesnot allow cookies for the webapp.

Goto Safari Preferences > Privacy > Cookies and website data > Allow all

Please confirm that this works.

**Comment by maticrivo** [comment]
It works now, but it's a privacy issue to allow all.
The webapp works fine if i go to http://crushingcode.byethost5.com/ and not http://javadocthemer.crushingcode.co without setting the cookies to allow all.

**Comment by nisrulz** [comment]
@maticrivo Thank you for pointing that out. I didnot notice that. Let me see why this is happening.

**Comment by nisrulz** [comment]
Checked and found some issue in DNS settings causing the issue because of forwarding with masking.
For now fixed this by disabling forwarding with masking in DNS settings. Now the [http://javadocthemer.crushingcode.co](http://javadocthemer.crushingcode.co) forwards to [http://crushingcode.byethost5.com](http://crushingcode.byethost5.com/)

Tested it on Safari, Mozilla, Opera and Chrome browser to be working. You do not have to make any changes to your cookie settings.

Please confirm this and close the issue.

**Comment by maticrivo** [comment]
works.
