### ISSUE TITLE
Feature Request: Dark theme support?

### ISSUE THREAD

**Issue by ghost** [nisrulz/javadoc-themer#3]

**Comment by nisrulz** [comment]
I will take a look at it. This project is quite old and frankly I didn't even know if anyone was using it. I built this for myself at the time. 

To be clear about this dark theme, it won't be something you can toggle i.e once generated the theme would just be that, with the dark them. If you need the white theme you would need to generate again.

The reason is simple, I don't modify the generated javadoc html files at all. Instead I inject the stylesheet i.e css.
